import {selectProducts,cleanCart,cartSummary,normalize} from './core.mjs';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
const products=window.CATALOG||[];let cart=[];try{cart=cleanCart(JSON.parse(localStorage.getItem('michaels-stash-v1')||'[]'),products)}catch{}let limit=24,letter='',category='All',toastTimer;
const params=new URLSearchParams(location.search);
const fields=['search','platform','decade','region','condition','sort'];
$('#platform').insertAdjacentHTML('beforeend',[...new Set(products.map(p=>p.platform))].sort().map(p=>`<option>${esc(p)}</option>`).join(''));
fields.forEach(k=>{if(params.has(k))$('#'+k).value=params.get(k)});if(!$('#sort').value)$('#sort').value='featured';category=params.get('category')||'All';letter=params.get('letter')||'';
$('#collection-count').textContent=`${products.length} FINDS · ${new Set(products.map(p=>p.platform)).size} SYSTEMS`;
$('#alphabet').innerHTML=['All','#',...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'].map(l=>`<button data-letter="${l==='All'?'':l}" aria-pressed="false">${l}</button>`).join('');
function persist(){try{localStorage.setItem('michaels-stash-v1',JSON.stringify(cart))}catch{}$('#cart-count').textContent=cart.length;document.querySelectorAll('.stash-add').forEach(b=>{const added=cart.includes(b.dataset.add);b.classList.toggle('added',added);b.textContent=added?'✓':'+';b.setAttribute('aria-label',`${added?'Remove':'Add'} ${products.find(p=>p.id===b.dataset.add)?.title} ${added?'from':'to'} your stash`);b.setAttribute('aria-pressed',added)})}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
function add(id){if(!products.some(p=>p.id===id))return;const existing=cart.includes(id);cart=existing?cart.filter(x=>x!==id):[...cart,id];persist();toast(existing?'Removed from your stash.':'Good find. Saved to your stash!');if($('#cart').open)renderCart();const b=$('#detail [data-detail-add]');if(b&&b.dataset.detailAdd===id)b.textContent=cart.includes(id)?'Remove from stash −':'Add to my stash +'}
function render(){const filters={q:$('#search').value,platform:$('#platform').value,decade:$('#decade').value,region:$('#region').value,condition:$('#condition').value,sort:$('#sort').value,letter,category};const list=selectProducts(products,filters);const shown=list.slice(0,limit);$('#results-count').textContent=`${list.length} ${list.length===1?'find':'finds'}${filters.q?' for “'+filters.q+'”':''}`;
 document.querySelectorAll('.category-tabs button').forEach(b=>{b.classList.toggle('active',b.dataset.category===category);b.setAttribute('aria-pressed',b.dataset.category===category)});document.querySelectorAll('[data-letter]').forEach(b=>{b.classList.toggle('active',b.dataset.letter===letter);b.setAttribute('aria-pressed',b.dataset.letter===letter)});
 $('#products').innerHTML=shown.length?shown.map(p=>`<article class="product"><button class="product-view" data-detail="${p.id}" aria-label="View ${esc(p.title)} for ${esc(p.platform)}"><div class="product-photo ${p.crop?'':'shelf'}"><img src="${esc(p.image)}" loading="lazy" decoding="async" alt="${esc(p.title)} — ${p.crop?'item cropped from':'shown in'} collection photo"><span class="photo-label">${p.region==='Japan'?'JAPAN IMPORT':p.category==='Consoles'?'HARDWARE':p.year&&p.year<2000?'RETRO FIND':p.region==='PAL'?'PAL IMPORT':'FROM THE VAULT'}</span></div><div class="product-info"><div class="platform-line"><span>${esc(p.platform.toUpperCase())}</span><span>${p.year||'YEAR TBD'}</span></div><h3>${esc(p.title)}</h3><p class="format">${p.condition==='Loose'?'Loose cartridge / disc':'Box / case shown'} · ${esc(p.region)}</p></div></button><div class="product-bottom"><div><span class="price ${p.priceCents===null?'pending':''}">${p.priceCents===null?'Price under review':money(p.priceCents)}</span>${p.priceCents!==null?'<span class="price-label">Market reference + 5%</span>':''}</div><button class="stash-add" data-add="${p.id}" aria-label="Add ${esc(p.title)} to your stash">+</button></div></article>`).join(''):`<div class="empty"><div class="icon">✧</div><h2>${['Coins','History'].includes(category)?'A new chapter is coming.':'No finds in this orbit.'}</h2><p>${['Coins','History'].includes(category)?'Photos for this collection haven’t arrived yet.<br>There are plenty of games and consoles to explore.':'Try another title, console, decade, or letter.'}</p><button class="secondary" id="empty-reset">Explore everything ↗</button></div>`;
 $('#load-more').hidden=limit>=list.length;$('#shown-count').textContent=list.length?`Showing ${shown.length} of ${list.length} finds`:'';persist();const url=new URL(location.href);fields.forEach(k=>{const v=$('#'+k).value;if(v&&!(k==='sort'&&v==='featured'))url.searchParams.set(k,v);else url.searchParams.delete(k)});if(category!=='All')url.searchParams.set('category',category);else url.searchParams.delete('category');if(letter)url.searchParams.set('letter',letter);else url.searchParams.delete('letter');try{history.replaceState({},'',url)}catch{}
}
function reset(){fields.forEach(k=>$('#'+k).value=k==='sort'?'featured':'');category='All';letter='';limit=24;render()}
function details(id){const p=products.find(x=>x.id===id);if(!p)return;$('#detail-content').innerHTML=`<div class="detail-layout"><div><img class="detail-image" src="${esc(p.image)}" alt="${esc(p.title)} from the collection"><a class="source-link" href="assets/photos/${esc(p.photo.replace('.jpg','.webp'))}" target="_blank" rel="noopener">Inspect the complete source photo ↗</a><p class="fine">${esc(p.photo)} · ${p.crop?'Photo crop of this item.':'Shared shelf photo; this listing is for the named item only.'}</p></div><div><div class="eyebrow">${esc(p.category.toUpperCase())} / ${esc(p.region.toUpperCase())}</div><h2 id="detail-title">${esc(p.title)}</h2><dl><dt>Console</dt><dd>${esc(p.platform)}</dd><dt>Release year</dt><dd>${p.year||'To verify'}${p.year&&p.releaseYearStatus!=='Source checked'?' (to verify)':''}</dd><dt>Format</dt><dd>${p.condition==='Loose'?'Loose':'Complete assumed from case'}</dd><dt>Availability</dt><dd>Seller confirmation pending</dd></dl><div class="price ${p.priceCents===null?'pending':''}">${p.priceCents===null?'Price under review':money(p.priceCents)}</div>${p.priceCents!==null?`<p class="fine">Market reference ${money(p.marketCents)} × 1.05.<br>${p.condition==='Loose'?'Loose':'Complete-in-box'} reference, checked ${esc(p.priceChecked)}.<br><a href="${esc(p.priceSource)}" target="_blank" rel="noopener">View pricing source ↗</a></p>`:'<p>A matching edition and price reference are still being checked. You can save this find to your stash.</p>'}<p>${esc(p.notes)}</p>${p.condition!=='Loose'?'<p class="fine">Complete-in-box is a pricing assumption. Manuals and all original contents are not yet verified.</p>':''}<p class="fine">${p.region==='Japan'?'Japanese release. Language and console compatibility should be checked.':p.region==='PAL'?'PAL release. Check region and display compatibility.':''}</p><button class="primary" data-detail-add="${p.id}">${cart.includes(id)?'Remove from stash −':'Add to my stash +'}</button><p class="fine">USPS shipping quoted separately. Preview only; saving does not reserve this item.</p></div></div>`;if(!$('#detail').open)$('#detail').showModal()}
function shipping(){ $('#shipping-info').textContent=$('#shipping').value==='domestic'?'USPS Ground Advantage / Priority Mail. Shipping quote pending packed weight, dimensions, and destination ZIP.':'Eligible USPS international service. Shipping quote pending destination country, packed weight, and dimensions. Customs charges and destination restrictions may apply.';}
function renderCart(){const s=cartSummary(cart,products);$('#cart-items').innerHTML=s.list.length?s.list.map(p=>`<div class="cart-line"><img src="${esc(p.image)}" alt=""><div><h3>${esc(p.title)}</h3><p>${esc(p.platform)} · ${esc(p.region)}</p><p>${p.priceCents===null?'Price under review':money(p.priceCents)}</p></div><button class="remove" data-remove="${p.id}" aria-label="Remove ${esc(p.title)}">Remove</button></div>`).join(''):'<div class="empty"><div class="icon">✧</div><p>Your next favorite is out there.<br>Add a find to start your stash.</p></div>';$('#cart-summary').innerHTML=s.list.length?`Priced items subtotal <strong>${money(s.knownSubtotal)}</strong>${s.pending?`<p class="fine">${s.pending} ${s.pending===1?'item needs':'items need'} a price and is not included above.</p>`:''}<p class="fine">Shipping and applicable taxes are not included.</p>`:'';$('#download').disabled=!s.list.length;shipping()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.detail)details(b.dataset.detail);if(b.dataset.add)add(b.dataset.add);if(b.dataset.detailAdd)add(b.dataset.detailAdd);if(b.dataset.remove){cart=cart.filter(id=>id!==b.dataset.remove);persist();renderCart()}if('letter'in b.dataset){letter=b.dataset.letter;limit=24;render()}if(b.dataset.category){category=b.dataset.category;limit=24;render();$('#collection').scrollIntoView()}if(b.id==='empty-reset')reset();if(b.classList.contains('close'))b.closest('dialog').close()});
fields.forEach(k=>$('#'+k).addEventListener(k==='search'?'input':'change',()=>{limit=24;render()}));$('#reset').onclick=reset;$('#load-more').onclick=()=>{limit+=24;render()};$('#random').onclick=()=>details(products[Math.floor(Math.random()*products.length)].id);$('#cart-open').onclick=()=>{renderCart();$('#cart').showModal()};$('#shipping').onchange=shipping;
$('#download').onclick=()=>{const s=cartSummary(cart,products);const lines=["MICHAEL'S STUFF — SAVED SELECTION",'This is a shopping list, not an order or reservation.','',...s.list.map(p=>`${p.title} | ${p.platform} | ${p.region} | ${p.condition} | ${p.priceCents===null?'Price pending':money(p.priceCents)} | SKU ${p.id}`),'',`Priced items subtotal: ${money(s.knownSubtotal)}`,`Unpriced items: ${s.pending}`,`Shipping: ${$('#shipping').value==='domestic'?'United States':'International'} via USPS — quote pending`,'Taxes: pending','Stock, contents and working condition: seller confirmation required.'];const a=document.createElement('a');const u=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain'}));a.href=u;a.download='michaels-stuff-selection.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Selection downloaded. No order has been placed.')};
$('#photo-open').onclick=()=>{$('#archive-grid').innerHTML=(window.PHOTOS||[]).map(p=>`<a href="${esc(p.web)}" target="_blank" rel="noopener"><img src="${esc(p.web)}" alt="Collection photo ${esc(p.file)}" loading="lazy">${esc(p.file)}</a>`).join('');$('#archive').showModal()};
document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('#search').focus();$('#collection').scrollIntoView()}});
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
render();
const canvas=$('#stars'),ctx=canvas.getContext('2d');let stars=[],moving=!matchMedia('(prefers-reduced-motion: reduce)').matches,raf,last=0;
function size(){const ratio=Math.min(devicePixelRatio,2);canvas.width=innerWidth*ratio;canvas.height=innerHeight*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);stars=Array.from({length:Math.min(150,Math.floor(innerWidth/8))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.1+.3,v:Math.random()*.09+.02}));draw()}
function draw(t=0){ctx.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){ctx.fillStyle=`rgba(210,193,249,${.25+s.r/3})`;ctx.fillRect(s.x,s.y,s.r,s.r);if(moving&&t-last>12)s.y=(s.y+s.v)%innerHeight}last=t;if(moving&&!document.hidden)raf=requestAnimationFrame(draw)}
function motionLabel(){$('#motion').textContent=moving?'Pause starfield':'Play starfield'}$('#motion').onclick=()=>{moving=!moving;cancelAnimationFrame(raf);motionLabel();draw()};window.addEventListener('resize',()=>{cancelAnimationFrame(raf);size()});document.addEventListener('visibilitychange',()=>{cancelAnimationFrame(raf);if(!document.hidden)draw()});motionLabel();size();
